// Copyright The MatrixHub Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package syncpolicy

import (
	"testing"

	"github.com/matrixhub-ai/matrixhub/internal/domain/syncjob"
)

func TestSyncJobGenerator_Generate(t *testing.T) {
	tests := []struct {
		name          string
		policy        *SyncPolicy
		wantTaskCheck func(t *testing.T, task *SyncTask)
		wantJobsCount int
		wantJobCheck  func(t *testing.T, job *syncjob.SyncJob)
	}{
		{
			name: "pull base with explicit local resource name",
			policy: &SyncPolicy{
				ID:                 1,
				PolicyType:         SyncPolicyTypePull,
				TriggerType:        TriggerTypeManual,
				RegistryID:         2,
				RemoteProjectName:  "hf",
				RemoteResourceName: "gpt2",
				LocalProjectName:   "myproject",
				LocalResourceName:  "mygpt2",
				ResourceTypes:      "model",
			},
			wantTaskCheck: func(t *testing.T, task *SyncTask) {
				if task.SyncPolicyID != 1 {
					t.Errorf("task.SyncPolicyID = %d, want 1", task.SyncPolicyID)
				}
				if task.TriggerType != TriggerTypeManual {
					t.Errorf("task.TriggerType = %v, want Manual", task.TriggerType)
				}
				if task.Status != SyncTaskStatusRunning {
					t.Errorf("task.Status = %v, want Running", task.Status)
				}
				if task.TotalItems != 1 {
					t.Errorf("task.TotalItems = %d, want 1", task.TotalItems)
				}
				if task.StartedTimestamp == 0 {
					t.Error("task.StartedTimestamp should be set")
				}
			},
			wantJobsCount: 1,
			wantJobCheck: func(t *testing.T, job *syncjob.SyncJob) {
				if job.RemoteRegistryID != 2 {
					t.Errorf("job.RemoteRegistryID = %d, want 2", job.RemoteRegistryID)
				}
				if job.RemoteProjectName != "hf" {
					t.Errorf("job.RemoteProjectName = %s, want hf", job.RemoteProjectName)
				}
				if job.RemoteResourceName != "gpt2" {
					t.Errorf("job.RemoteResourceName = %s, want gpt2", job.RemoteResourceName)
				}
				if job.ProjectName != "myproject" {
					t.Errorf("job.ProjectName = %s, want myproject", job.ProjectName)
				}
				if job.ResourceName != "mygpt2" {
					t.Errorf("job.ResourceName = %s, want mygpt2", job.ResourceName)
				}
				if job.ResourceType != "model" {
					t.Errorf("job.ResourceType = %s, want model", job.ResourceType)
				}
				if job.SyncType != "pull" {
					t.Errorf("job.SyncType = %s, want pull", job.SyncType)
				}
				if job.Status != syncjob.SyncJobStatusRunning {
					t.Errorf("job.Status = %v, want Running", job.Status)
				}
			},
		},
		{
			name: "pull base without local resource name — auto-generated by generator",
			policy: &SyncPolicy{
				ID:                 2,
				PolicyType:         SyncPolicyTypePull,
				TriggerType:        TriggerTypeManual,
				RegistryID:         3,
				RemoteProjectName:  "openai",
				RemoteResourceName: "whisper",
				LocalProjectName:   "myproject",
				LocalResourceName:  "",
				ResourceTypes:      "dataset",
			},
			wantTaskCheck: func(t *testing.T, task *SyncTask) {
				if task.SyncPolicyID != 2 {
					t.Errorf("task.SyncPolicyID = %d, want 2", task.SyncPolicyID)
				}
				if task.TotalItems != 1 {
					t.Errorf("task.TotalItems = %d, want 1", task.TotalItems)
				}
			},
			wantJobsCount: 1,
			wantJobCheck: func(t *testing.T, job *syncjob.SyncJob) {
				if job.ResourceName != "whisper" {
					t.Errorf("job.ResourceName = %s, want whisper (auto-generated from remote)", job.ResourceName)
				}
				if job.ProjectName != "myproject" {
					t.Errorf("job.ProjectName = %s, want myproject", job.ProjectName)
				}
				if job.SyncType != "pull" {
					t.Errorf("job.SyncType = %s, want pull", job.SyncType)
				}
			},
		},
		{
			name: "push base",
			policy: &SyncPolicy{
				ID:                 3,
				PolicyType:         SyncPolicyTypePush,
				TriggerType:        TriggerTypeManual,
				RegistryID:         4,
				LocalProjectName:   "myproject",
				LocalResourceName:  "mygpt2",
				RemoteProjectName:  "hf",
				RemoteResourceName: "gpt2",
				ResourceTypes:      "model,dataset",
			},
			wantTaskCheck: func(t *testing.T, task *SyncTask) {
				if task.SyncPolicyID != 3 {
					t.Errorf("task.SyncPolicyID = %d, want 3", task.SyncPolicyID)
				}
				if task.TotalItems != 2 {
					t.Errorf("task.TotalItems = %d, want 2", task.TotalItems)
				}
			},
			wantJobsCount: 2,
			wantJobCheck: func(t *testing.T, job *syncjob.SyncJob) {
				if job.RemoteRegistryID != 4 {
					t.Errorf("job.RemoteRegistryID = %d, want 4", job.RemoteRegistryID)
				}
				if job.SyncType != "push" {
					t.Errorf("job.SyncType = %s, want push", job.SyncType)
				}
				if job.ProjectName != "myproject" {
					t.Errorf("job.ProjectName = %s, want myproject", job.ProjectName)
				}
				if job.ResourceName != "mygpt2" {
					t.Errorf("job.ResourceName = %s, want mygpt2", job.ResourceName)
				}
			},
		},
		{
			name: "empty resource types defaults to model",
			policy: &SyncPolicy{
				ID:                 4,
				PolicyType:         SyncPolicyTypePull,
				TriggerType:        TriggerTypeManual,
				RegistryID:         5,
				RemoteProjectName:  "hf",
				RemoteResourceName: "bert",
				LocalProjectName:   "proj",
				LocalResourceName:  "",
				ResourceTypes:      "",
			},
			wantTaskCheck: func(t *testing.T, task *SyncTask) {
				if task.TotalItems != 1 {
					t.Errorf("task.TotalItems = %d, want 1", task.TotalItems)
				}
			},
			wantJobsCount: 1,
			wantJobCheck: func(t *testing.T, job *syncjob.SyncJob) {
				if job.ResourceType != "model" {
					t.Errorf("job.ResourceType = %s, want model", job.ResourceType)
				}
			},
		},
		{
			name: "resource type 'all' expands to model and dataset",
			policy: &SyncPolicy{
				ID:                 5,
				PolicyType:         SyncPolicyTypePull,
				TriggerType:        TriggerTypeScheduled,
				RegistryID:         6,
				RemoteProjectName:  "hf",
				RemoteResourceName: "llama",
				LocalProjectName:   "proj",
				LocalResourceName:  "",
				ResourceTypes:      "all",
			},
			wantTaskCheck: func(t *testing.T, task *SyncTask) {
				if task.TotalItems != 2 {
					t.Errorf("task.TotalItems = %d, want 2", task.TotalItems)
				}
			},
			wantJobsCount: 2,
			wantJobCheck: func(t *testing.T, job *syncjob.SyncJob) {
				if job.ResourceType != "model" && job.ResourceType != "dataset" {
					t.Errorf("job.ResourceType = %s, want model or dataset", job.ResourceType)
				}
			},
		},
	}

	g := NewSyncJobGenerator()
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			task, jobs, err := g.Generate(t.Context(), tt.policy)
			if err != nil {
				t.Fatalf("Generate() error = %v", err)
			}

			if tt.wantTaskCheck != nil {
				tt.wantTaskCheck(t, task)
			}

			if len(jobs) != tt.wantJobsCount {
				t.Fatalf("got %d jobs, want %d", len(jobs), tt.wantJobsCount)
			}

			if tt.wantJobCheck != nil {
				for _, job := range jobs {
					tt.wantJobCheck(t, job)
				}
			}
		})
	}
}
