/*
 * v1alpha1/project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1MemberToRemove struct {
	MemberType *V1alpha1MemberType `json:"memberType,omitempty"`
	MemberId int32 `json:"memberId,omitempty"`
}
