/*
 * v1alpha1/current_user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1SshKeyStatus string

// List of v1alpha1SSHKeyStatus
const (
	UNKNOWN_V1alpha1SshKeyStatus V1alpha1SshKeyStatus = "SSH_KEY_STATUS_UNKNOWN"
	VALID_V1alpha1SshKeyStatus V1alpha1SshKeyStatus = "SSH_KEY_STATUS_VALID"
	EXPIRED_V1alpha1SshKeyStatus V1alpha1SshKeyStatus = "SSH_KEY_STATUS_EXPIRED"
)
