/*
 * v1alpha1/sync_policy.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1SyncPolicyItem struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	PolicyType *V1alpha1SyncPolicyType `json:"policyType,omitempty"`
	TriggerType *V1alpha1TriggerType `json:"triggerType,omitempty"`
	PullBasePolicy *V1alpha1PullBasePolicy `json:"pullBasePolicy,omitempty"`
	PushBasePolicy *V1alpha1PushBasePolicy `json:"pushBasePolicy,omitempty"`
	// The bandwidth to use for the sync policy.
	Bandwidth string `json:"bandwidth,omitempty"`
	IsOverwrite bool `json:"isOverwrite,omitempty"`
	IsDisabled bool `json:"isDisabled,omitempty"`
	TriggerTypeSchedule *V1alpha1TriggerTypeSchedule `json:"triggerTypeSchedule,omitempty"`
}
