/*
 * v1alpha1/sync_policy.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1SyncJobStatus string

// List of v1alpha1SyncJobStatus
const (
	UNSPECIFIED_V1alpha1SyncJobStatus V1alpha1SyncJobStatus = "SYNC_JOB_STATUS_UNSPECIFIED"
	RUNNING_V1alpha1SyncJobStatus V1alpha1SyncJobStatus = "SYNC_JOB_STATUS_RUNNING"
	SUCCEEDED_V1alpha1SyncJobStatus V1alpha1SyncJobStatus = "SYNC_JOB_STATUS_SUCCEEDED"
	FAILED_V1alpha1SyncJobStatus V1alpha1SyncJobStatus = "SYNC_JOB_STATUS_FAILED"
	STOPPED_V1alpha1SyncJobStatus V1alpha1SyncJobStatus = "SYNC_JOB_STATUS_STOPPED"
)
