/*
 * v1alpha1/sync_policy.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1PushBasePolicy struct {
	ResourceName string `json:"resourceName,omitempty"`
	ResourceTypes []V1alpha1ResourceType `json:"resourceTypes,omitempty"`
	TargetRegistryId int64 `json:"targetRegistryId,omitempty"`
	TargetRegistry *V1alpha1Registry `json:"targetRegistry,omitempty"`
	TargetProjectName string `json:"targetProjectName,omitempty"`
}
