/*
 * v1alpha1/sync_policy.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1TriggerTypeSchedule struct {
	Cron string `json:"cron,omitempty"`
}
