/*
 * v1alpha1/role.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1RoleCategory struct {
	Name string `json:"name,omitempty"`
	Permissions []V1alpha1Permission `json:"permissions,omitempty"`
}
