/*
 * v1alpha1/robot.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1RobotAccountProjectScope string

// List of v1alpha1RobotAccountProjectScope
const (
	SELECTED_V1alpha1RobotAccountProjectScope V1alpha1RobotAccountProjectScope = "ROBOT_ACCOUNT_PROJECT_SCOPE_SELECTED"
	ALL_V1alpha1RobotAccountProjectScope V1alpha1RobotAccountProjectScope = "ROBOT_ACCOUNT_PROJECT_SCOPE_ALL"
)
