/*
 * v1alpha1/robot.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ListRobotAccountsResponse struct {
	Items []V1alpha1GetRobotAccountResponse `json:"items,omitempty"`
	Pagination *V1alpha1Pagination `json:"pagination,omitempty"`
}
