/*
 * v1alpha1/robot.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1CreateRobotAccountResponse struct {
	Token string `json:"token,omitempty"`
}
