/*
 * v1alpha1/robot.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type RobotsUpdateRobotAccountBody struct {
	Description string `json:"description,omitempty"`
	Status *V1alpha1RobotAccountStatus `json:"status,omitempty"`
	PlatformPermissions []string `json:"platformPermissions,omitempty"`
	ProjectPermissions []string `json:"projectPermissions,omitempty"`
	Projects []string `json:"projects,omitempty"`
	ProjectScope *V1alpha1RobotAccountProjectScope `json:"projectScope,omitempty"`
	ExpireDays int32 `json:"expireDays,omitempty"`
}
