// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/robot.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Robots_CreateRobotAccount_FullMethodName       = "/matrixhub.v1alpha1.Robots/CreateRobotAccount"
	Robots_ListRobotAccounts_FullMethodName        = "/matrixhub.v1alpha1.Robots/ListRobotAccounts"
	Robots_GetRobotAccount_FullMethodName          = "/matrixhub.v1alpha1.Robots/GetRobotAccount"
	Robots_DeleteRobotAccount_FullMethodName       = "/matrixhub.v1alpha1.Robots/DeleteRobotAccount"
	Robots_UpdateRobotAccount_FullMethodName       = "/matrixhub.v1alpha1.Robots/UpdateRobotAccount"
	Robots_RefreshRobotAccountToken_FullMethodName = "/matrixhub.v1alpha1.Robots/RefreshRobotAccountToken"
)

// RobotsClient is the client API for Robots service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotsClient interface {
	CreateRobotAccount(ctx context.Context, in *CreateRobotAccountRequest, opts ...grpc.CallOption) (*CreateRobotAccountResponse, error)
	ListRobotAccounts(ctx context.Context, in *ListRobotAccountsRequest, opts ...grpc.CallOption) (*ListRobotAccountsResponse, error)
	GetRobotAccount(ctx context.Context, in *GetRobotAccountRequest, opts ...grpc.CallOption) (*GetRobotAccountResponse, error)
	DeleteRobotAccount(ctx context.Context, in *DeleteRobotAccountRequest, opts ...grpc.CallOption) (*DeleteRobotAccountResponse, error)
	UpdateRobotAccount(ctx context.Context, in *UpdateRobotAccountRequest, opts ...grpc.CallOption) (*UpdateRobotAccountResponse, error)
	RefreshRobotAccountToken(ctx context.Context, in *RefreshRobotAccountTokenRequest, opts ...grpc.CallOption) (*RefreshRobotAccountTokenResponse, error)
}

type robotsClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotsClient(cc grpc.ClientConnInterface) RobotsClient {
	return &robotsClient{cc}
}

func (c *robotsClient) CreateRobotAccount(ctx context.Context, in *CreateRobotAccountRequest, opts ...grpc.CallOption) (*CreateRobotAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRobotAccountResponse)
	err := c.cc.Invoke(ctx, Robots_CreateRobotAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsClient) ListRobotAccounts(ctx context.Context, in *ListRobotAccountsRequest, opts ...grpc.CallOption) (*ListRobotAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRobotAccountsResponse)
	err := c.cc.Invoke(ctx, Robots_ListRobotAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsClient) GetRobotAccount(ctx context.Context, in *GetRobotAccountRequest, opts ...grpc.CallOption) (*GetRobotAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRobotAccountResponse)
	err := c.cc.Invoke(ctx, Robots_GetRobotAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsClient) DeleteRobotAccount(ctx context.Context, in *DeleteRobotAccountRequest, opts ...grpc.CallOption) (*DeleteRobotAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRobotAccountResponse)
	err := c.cc.Invoke(ctx, Robots_DeleteRobotAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsClient) UpdateRobotAccount(ctx context.Context, in *UpdateRobotAccountRequest, opts ...grpc.CallOption) (*UpdateRobotAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRobotAccountResponse)
	err := c.cc.Invoke(ctx, Robots_UpdateRobotAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsClient) RefreshRobotAccountToken(ctx context.Context, in *RefreshRobotAccountTokenRequest, opts ...grpc.CallOption) (*RefreshRobotAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshRobotAccountTokenResponse)
	err := c.cc.Invoke(ctx, Robots_RefreshRobotAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotsServer is the server API for Robots service.
// All implementations should embed UnimplementedRobotsServer
// for forward compatibility.
type RobotsServer interface {
	CreateRobotAccount(context.Context, *CreateRobotAccountRequest) (*CreateRobotAccountResponse, error)
	ListRobotAccounts(context.Context, *ListRobotAccountsRequest) (*ListRobotAccountsResponse, error)
	GetRobotAccount(context.Context, *GetRobotAccountRequest) (*GetRobotAccountResponse, error)
	DeleteRobotAccount(context.Context, *DeleteRobotAccountRequest) (*DeleteRobotAccountResponse, error)
	UpdateRobotAccount(context.Context, *UpdateRobotAccountRequest) (*UpdateRobotAccountResponse, error)
	RefreshRobotAccountToken(context.Context, *RefreshRobotAccountTokenRequest) (*RefreshRobotAccountTokenResponse, error)
}

// UnimplementedRobotsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotsServer struct{}

func (UnimplementedRobotsServer) CreateRobotAccount(context.Context, *CreateRobotAccountRequest) (*CreateRobotAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRobotAccount not implemented")
}
func (UnimplementedRobotsServer) ListRobotAccounts(context.Context, *ListRobotAccountsRequest) (*ListRobotAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRobotAccounts not implemented")
}
func (UnimplementedRobotsServer) GetRobotAccount(context.Context, *GetRobotAccountRequest) (*GetRobotAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRobotAccount not implemented")
}
func (UnimplementedRobotsServer) DeleteRobotAccount(context.Context, *DeleteRobotAccountRequest) (*DeleteRobotAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRobotAccount not implemented")
}
func (UnimplementedRobotsServer) UpdateRobotAccount(context.Context, *UpdateRobotAccountRequest) (*UpdateRobotAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRobotAccount not implemented")
}
func (UnimplementedRobotsServer) RefreshRobotAccountToken(context.Context, *RefreshRobotAccountTokenRequest) (*RefreshRobotAccountTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshRobotAccountToken not implemented")
}
func (UnimplementedRobotsServer) testEmbeddedByValue() {}

// UnsafeRobotsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotsServer will
// result in compilation errors.
type UnsafeRobotsServer interface {
	mustEmbedUnimplementedRobotsServer()
}

func RegisterRobotsServer(s grpc.ServiceRegistrar, srv RobotsServer) {
	// If the following call panics, it indicates UnimplementedRobotsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Robots_ServiceDesc, srv)
}

func _Robots_CreateRobotAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRobotAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).CreateRobotAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_CreateRobotAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).CreateRobotAccount(ctx, req.(*CreateRobotAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robots_ListRobotAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRobotAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).ListRobotAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_ListRobotAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).ListRobotAccounts(ctx, req.(*ListRobotAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robots_GetRobotAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRobotAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).GetRobotAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_GetRobotAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).GetRobotAccount(ctx, req.(*GetRobotAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robots_DeleteRobotAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRobotAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).DeleteRobotAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_DeleteRobotAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).DeleteRobotAccount(ctx, req.(*DeleteRobotAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robots_UpdateRobotAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRobotAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).UpdateRobotAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_UpdateRobotAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).UpdateRobotAccount(ctx, req.(*UpdateRobotAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robots_RefreshRobotAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRobotAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServer).RefreshRobotAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robots_RefreshRobotAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServer).RefreshRobotAccountToken(ctx, req.(*RefreshRobotAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Robots_ServiceDesc is the grpc.ServiceDesc for Robots service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Robots_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Robots",
	HandlerType: (*RobotsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRobotAccount",
			Handler:    _Robots_CreateRobotAccount_Handler,
		},
		{
			MethodName: "ListRobotAccounts",
			Handler:    _Robots_ListRobotAccounts_Handler,
		},
		{
			MethodName: "GetRobotAccount",
			Handler:    _Robots_GetRobotAccount_Handler,
		},
		{
			MethodName: "DeleteRobotAccount",
			Handler:    _Robots_DeleteRobotAccount_Handler,
		},
		{
			MethodName: "UpdateRobotAccount",
			Handler:    _Robots_UpdateRobotAccount_Handler,
		},
		{
			MethodName: "RefreshRobotAccountToken",
			Handler:    _Robots_RefreshRobotAccountToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/robot.proto",
}
