// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/robot.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateRobotAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRobotAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRobotAccountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRobotAccountRequestMultiError, or nil if none found.
func (m *CreateRobotAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRobotAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateRobotAccountRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := CreateRobotAccountRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ExpireDays

	// no validation rules for ProjectScope

	if len(errors) > 0 {
		return CreateRobotAccountRequestMultiError(errors)
	}

	return nil
}

// CreateRobotAccountRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRobotAccountRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateRobotAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRobotAccountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRobotAccountRequestMultiError) AllErrors() []error { return m }

// CreateRobotAccountRequestValidationError is the validation error returned by
// CreateRobotAccountRequest.Validate if the designated constraints aren't met.
type CreateRobotAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRobotAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRobotAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRobotAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRobotAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRobotAccountRequestValidationError) ErrorName() string {
	return "CreateRobotAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRobotAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRobotAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRobotAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRobotAccountRequestValidationError{}

// Validate checks the field values on CreateRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRobotAccountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRobotAccountResponseMultiError, or nil if none found.
func (m *CreateRobotAccountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRobotAccountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return CreateRobotAccountResponseMultiError(errors)
	}

	return nil
}

// CreateRobotAccountResponseMultiError is an error wrapping multiple
// validation errors returned by CreateRobotAccountResponse.ValidateAll() if
// the designated constraints aren't met.
type CreateRobotAccountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRobotAccountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRobotAccountResponseMultiError) AllErrors() []error { return m }

// CreateRobotAccountResponseValidationError is the validation error returned
// by CreateRobotAccountResponse.Validate if the designated constraints aren't met.
type CreateRobotAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRobotAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRobotAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRobotAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRobotAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRobotAccountResponseValidationError) ErrorName() string {
	return "CreateRobotAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRobotAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRobotAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRobotAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRobotAccountResponseValidationError{}

// Validate checks the field values on ListRobotAccountsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRobotAccountsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRobotAccountsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRobotAccountsRequestMultiError, or nil if none found.
func (m *ListRobotAccountsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRobotAccountsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Search

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListRobotAccountsRequestMultiError(errors)
	}

	return nil
}

// ListRobotAccountsRequestMultiError is an error wrapping multiple validation
// errors returned by ListRobotAccountsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRobotAccountsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRobotAccountsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRobotAccountsRequestMultiError) AllErrors() []error { return m }

// ListRobotAccountsRequestValidationError is the validation error returned by
// ListRobotAccountsRequest.Validate if the designated constraints aren't met.
type ListRobotAccountsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRobotAccountsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRobotAccountsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRobotAccountsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRobotAccountsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRobotAccountsRequestValidationError) ErrorName() string {
	return "ListRobotAccountsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRobotAccountsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRobotAccountsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRobotAccountsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRobotAccountsRequestValidationError{}

// Validate checks the field values on ListRobotAccountsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRobotAccountsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRobotAccountsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRobotAccountsResponseMultiError, or nil if none found.
func (m *ListRobotAccountsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRobotAccountsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRobotAccountsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRobotAccountsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRobotAccountsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListRobotAccountsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListRobotAccountsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListRobotAccountsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListRobotAccountsResponseMultiError(errors)
	}

	return nil
}

// ListRobotAccountsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRobotAccountsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListRobotAccountsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRobotAccountsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRobotAccountsResponseMultiError) AllErrors() []error { return m }

// ListRobotAccountsResponseValidationError is the validation error returned by
// ListRobotAccountsResponse.Validate if the designated constraints aren't met.
type ListRobotAccountsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRobotAccountsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRobotAccountsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRobotAccountsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRobotAccountsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRobotAccountsResponseValidationError) ErrorName() string {
	return "ListRobotAccountsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRobotAccountsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRobotAccountsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRobotAccountsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRobotAccountsResponseValidationError{}

// Validate checks the field values on RobotAccount with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RobotAccount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RobotAccount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RobotAccountMultiError, or
// nil if none found.
func (m *RobotAccount) ValidateAll() error {
	return m.validate(true)
}

func (m *RobotAccount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for ExpireStatus

	// no validation rules for RemainPeriod

	// no validation rules for ExpireDays

	// no validation rules for ProjectScope

	if len(errors) > 0 {
		return RobotAccountMultiError(errors)
	}

	return nil
}

// RobotAccountMultiError is an error wrapping multiple validation errors
// returned by RobotAccount.ValidateAll() if the designated constraints aren't met.
type RobotAccountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RobotAccountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RobotAccountMultiError) AllErrors() []error { return m }

// RobotAccountValidationError is the validation error returned by
// RobotAccount.Validate if the designated constraints aren't met.
type RobotAccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RobotAccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RobotAccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RobotAccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RobotAccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RobotAccountValidationError) ErrorName() string { return "RobotAccountValidationError" }

// Error satisfies the builtin error interface
func (e RobotAccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRobotAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RobotAccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RobotAccountValidationError{}

// Validate checks the field values on GetRobotAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRobotAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRobotAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRobotAccountRequestMultiError, or nil if none found.
func (m *GetRobotAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRobotAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetRobotAccountRequestMultiError(errors)
	}

	return nil
}

// GetRobotAccountRequestMultiError is an error wrapping multiple validation
// errors returned by GetRobotAccountRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRobotAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRobotAccountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRobotAccountRequestMultiError) AllErrors() []error { return m }

// GetRobotAccountRequestValidationError is the validation error returned by
// GetRobotAccountRequest.Validate if the designated constraints aren't met.
type GetRobotAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRobotAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRobotAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRobotAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRobotAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRobotAccountRequestValidationError) ErrorName() string {
	return "GetRobotAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRobotAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRobotAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRobotAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRobotAccountRequestValidationError{}

// Validate checks the field values on GetRobotAccountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRobotAccountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRobotAccountResponseMultiError, or nil if none found.
func (m *GetRobotAccountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRobotAccountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for ExpireStatus

	// no validation rules for RemainPeriod

	// no validation rules for ExpireDays

	// no validation rules for ProjectScope

	if len(errors) > 0 {
		return GetRobotAccountResponseMultiError(errors)
	}

	return nil
}

// GetRobotAccountResponseMultiError is an error wrapping multiple validation
// errors returned by GetRobotAccountResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRobotAccountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRobotAccountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRobotAccountResponseMultiError) AllErrors() []error { return m }

// GetRobotAccountResponseValidationError is the validation error returned by
// GetRobotAccountResponse.Validate if the designated constraints aren't met.
type GetRobotAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRobotAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRobotAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRobotAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRobotAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRobotAccountResponseValidationError) ErrorName() string {
	return "GetRobotAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRobotAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRobotAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRobotAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRobotAccountResponseValidationError{}

// Validate checks the field values on DeleteRobotAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRobotAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRobotAccountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRobotAccountRequestMultiError, or nil if none found.
func (m *DeleteRobotAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRobotAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteRobotAccountRequestMultiError(errors)
	}

	return nil
}

// DeleteRobotAccountRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRobotAccountRequest.ValidateAll() if the
// designated constraints aren't met.
type DeleteRobotAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRobotAccountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRobotAccountRequestMultiError) AllErrors() []error { return m }

// DeleteRobotAccountRequestValidationError is the validation error returned by
// DeleteRobotAccountRequest.Validate if the designated constraints aren't met.
type DeleteRobotAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRobotAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRobotAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRobotAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRobotAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRobotAccountRequestValidationError) ErrorName() string {
	return "DeleteRobotAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRobotAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRobotAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRobotAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRobotAccountRequestValidationError{}

// Validate checks the field values on DeleteRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRobotAccountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRobotAccountResponseMultiError, or nil if none found.
func (m *DeleteRobotAccountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRobotAccountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteRobotAccountResponseMultiError(errors)
	}

	return nil
}

// DeleteRobotAccountResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteRobotAccountResponse.ValidateAll() if
// the designated constraints aren't met.
type DeleteRobotAccountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRobotAccountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRobotAccountResponseMultiError) AllErrors() []error { return m }

// DeleteRobotAccountResponseValidationError is the validation error returned
// by DeleteRobotAccountResponse.Validate if the designated constraints aren't met.
type DeleteRobotAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRobotAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRobotAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRobotAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRobotAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRobotAccountResponseValidationError) ErrorName() string {
	return "DeleteRobotAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRobotAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRobotAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRobotAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRobotAccountResponseValidationError{}

// Validate checks the field values on UpdateRobotAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRobotAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRobotAccountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRobotAccountRequestMultiError, or nil if none found.
func (m *UpdateRobotAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRobotAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for ProjectScope

	// no validation rules for ExpireDays

	if len(errors) > 0 {
		return UpdateRobotAccountRequestMultiError(errors)
	}

	return nil
}

// UpdateRobotAccountRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateRobotAccountRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateRobotAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRobotAccountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRobotAccountRequestMultiError) AllErrors() []error { return m }

// UpdateRobotAccountRequestValidationError is the validation error returned by
// UpdateRobotAccountRequest.Validate if the designated constraints aren't met.
type UpdateRobotAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRobotAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRobotAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRobotAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRobotAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRobotAccountRequestValidationError) ErrorName() string {
	return "UpdateRobotAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRobotAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRobotAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRobotAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRobotAccountRequestValidationError{}

// Validate checks the field values on UpdateRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRobotAccountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRobotAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRobotAccountResponseMultiError, or nil if none found.
func (m *UpdateRobotAccountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRobotAccountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateRobotAccountResponseMultiError(errors)
	}

	return nil
}

// UpdateRobotAccountResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateRobotAccountResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateRobotAccountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRobotAccountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRobotAccountResponseMultiError) AllErrors() []error { return m }

// UpdateRobotAccountResponseValidationError is the validation error returned
// by UpdateRobotAccountResponse.Validate if the designated constraints aren't met.
type UpdateRobotAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRobotAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRobotAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRobotAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRobotAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRobotAccountResponseValidationError) ErrorName() string {
	return "UpdateRobotAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRobotAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRobotAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRobotAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRobotAccountResponseValidationError{}

// Validate checks the field values on RefreshRobotAccountTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefreshRobotAccountTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshRobotAccountTokenRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RefreshRobotAccountTokenRequestMultiError, or nil if none found.
func (m *RefreshRobotAccountTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshRobotAccountTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AutoGenerate

	// no validation rules for Token

	if len(errors) > 0 {
		return RefreshRobotAccountTokenRequestMultiError(errors)
	}

	return nil
}

// RefreshRobotAccountTokenRequestMultiError is an error wrapping multiple
// validation errors returned by RefreshRobotAccountTokenRequest.ValidateAll()
// if the designated constraints aren't met.
type RefreshRobotAccountTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshRobotAccountTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshRobotAccountTokenRequestMultiError) AllErrors() []error { return m }

// RefreshRobotAccountTokenRequestValidationError is the validation error
// returned by RefreshRobotAccountTokenRequest.Validate if the designated
// constraints aren't met.
type RefreshRobotAccountTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshRobotAccountTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshRobotAccountTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshRobotAccountTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshRobotAccountTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshRobotAccountTokenRequestValidationError) ErrorName() string {
	return "RefreshRobotAccountTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RefreshRobotAccountTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshRobotAccountTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshRobotAccountTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshRobotAccountTokenRequestValidationError{}

// Validate checks the field values on RefreshRobotAccountTokenResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *RefreshRobotAccountTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshRobotAccountTokenResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RefreshRobotAccountTokenResponseMultiError, or nil if none found.
func (m *RefreshRobotAccountTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshRobotAccountTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return RefreshRobotAccountTokenResponseMultiError(errors)
	}

	return nil
}

// RefreshRobotAccountTokenResponseMultiError is an error wrapping multiple
// validation errors returned by
// RefreshRobotAccountTokenResponse.ValidateAll() if the designated
// constraints aren't met.
type RefreshRobotAccountTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshRobotAccountTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshRobotAccountTokenResponseMultiError) AllErrors() []error { return m }

// RefreshRobotAccountTokenResponseValidationError is the validation error
// returned by RefreshRobotAccountTokenResponse.Validate if the designated
// constraints aren't met.
type RefreshRobotAccountTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshRobotAccountTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshRobotAccountTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshRobotAccountTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshRobotAccountTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshRobotAccountTokenResponseValidationError) ErrorName() string {
	return "RefreshRobotAccountTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RefreshRobotAccountTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshRobotAccountTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshRobotAccountTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshRobotAccountTokenResponseValidationError{}
