// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/sync_policy.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncPolicy_ListSyncPolicies_FullMethodName = "/matrixhub.v1alpha1.SyncPolicy/ListSyncPolicies"
	SyncPolicy_GetSyncPolicy_FullMethodName    = "/matrixhub.v1alpha1.SyncPolicy/GetSyncPolicy"
	SyncPolicy_CreateSyncPolicy_FullMethodName = "/matrixhub.v1alpha1.SyncPolicy/CreateSyncPolicy"
	SyncPolicy_UpdateSyncPolicy_FullMethodName = "/matrixhub.v1alpha1.SyncPolicy/UpdateSyncPolicy"
	SyncPolicy_DeleteSyncPolicy_FullMethodName = "/matrixhub.v1alpha1.SyncPolicy/DeleteSyncPolicy"
	SyncPolicy_CreateSyncTask_FullMethodName   = "/matrixhub.v1alpha1.SyncPolicy/CreateSyncTask"
	SyncPolicy_ListSyncTasks_FullMethodName    = "/matrixhub.v1alpha1.SyncPolicy/ListSyncTasks"
	SyncPolicy_StopSyncTask_FullMethodName     = "/matrixhub.v1alpha1.SyncPolicy/StopSyncTask"
	SyncPolicy_ListSyncJobs_FullMethodName     = "/matrixhub.v1alpha1.SyncPolicy/ListSyncJobs"
	SyncPolicy_GetSyncJobLog_FullMethodName    = "/matrixhub.v1alpha1.SyncPolicy/GetSyncJobLog"
)

// SyncPolicyClient is the client API for SyncPolicy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncPolicyClient interface {
	// ListSyncPolicies lists all sync policies.
	ListSyncPolicies(ctx context.Context, in *ListSyncPoliciesRequest, opts ...grpc.CallOption) (*ListSyncPoliciesResponse, error)
	// GetSyncPolicy gets a sync policy by id.
	GetSyncPolicy(ctx context.Context, in *GetSyncPolicyRequest, opts ...grpc.CallOption) (*GetSyncPolicyResponse, error)
	// CreateSyncPolicy creates a new sync policy.
	CreateSyncPolicy(ctx context.Context, in *CreateSyncPolicyRequest, opts ...grpc.CallOption) (*CreateSyncPolicyResponse, error)
	// UpdateSyncPolicy updates a sync policy.
	UpdateSyncPolicy(ctx context.Context, in *UpdateSyncPolicyRequest, opts ...grpc.CallOption) (*UpdateSyncPolicyResponse, error)
	// DeleteSyncPolicy deletes a sync policy.
	DeleteSyncPolicy(ctx context.Context, in *DeleteSyncPolicyRequest, opts ...grpc.CallOption) (*DeleteSyncPolicyResponse, error)
	// CreateSyncTask creates a new sync task.
	CreateSyncTask(ctx context.Context, in *CreateSyncTaskRequest, opts ...grpc.CallOption) (*CreateSyncTaskResponse, error)
	// ListSyncTasks lists all sync tasks.
	ListSyncTasks(ctx context.Context, in *ListSyncTasksRequest, opts ...grpc.CallOption) (*ListSyncTasksResponse, error)
	// StopSyncTask stops a sync task.
	StopSyncTask(ctx context.Context, in *StopSyncTaskRequest, opts ...grpc.CallOption) (*StopSyncTaskResponse, error)
	// ListSyncJobs lists all sync jobs.
	ListSyncJobs(ctx context.Context, in *ListSyncJobsRequest, opts ...grpc.CallOption) (*ListSyncJobsResponse, error)
	// GetSyncJobLog gets the log of a sync job.
	GetSyncJobLog(ctx context.Context, in *GetSyncJobLogRequest, opts ...grpc.CallOption) (*GetSyncJobLogResponse, error)
}

type syncPolicyClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncPolicyClient(cc grpc.ClientConnInterface) SyncPolicyClient {
	return &syncPolicyClient{cc}
}

func (c *syncPolicyClient) ListSyncPolicies(ctx context.Context, in *ListSyncPoliciesRequest, opts ...grpc.CallOption) (*ListSyncPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSyncPoliciesResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_ListSyncPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) GetSyncPolicy(ctx context.Context, in *GetSyncPolicyRequest, opts ...grpc.CallOption) (*GetSyncPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncPolicyResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_GetSyncPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) CreateSyncPolicy(ctx context.Context, in *CreateSyncPolicyRequest, opts ...grpc.CallOption) (*CreateSyncPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSyncPolicyResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_CreateSyncPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) UpdateSyncPolicy(ctx context.Context, in *UpdateSyncPolicyRequest, opts ...grpc.CallOption) (*UpdateSyncPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSyncPolicyResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_UpdateSyncPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) DeleteSyncPolicy(ctx context.Context, in *DeleteSyncPolicyRequest, opts ...grpc.CallOption) (*DeleteSyncPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSyncPolicyResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_DeleteSyncPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) CreateSyncTask(ctx context.Context, in *CreateSyncTaskRequest, opts ...grpc.CallOption) (*CreateSyncTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSyncTaskResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_CreateSyncTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) ListSyncTasks(ctx context.Context, in *ListSyncTasksRequest, opts ...grpc.CallOption) (*ListSyncTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSyncTasksResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_ListSyncTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) StopSyncTask(ctx context.Context, in *StopSyncTaskRequest, opts ...grpc.CallOption) (*StopSyncTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSyncTaskResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_StopSyncTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) ListSyncJobs(ctx context.Context, in *ListSyncJobsRequest, opts ...grpc.CallOption) (*ListSyncJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSyncJobsResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_ListSyncJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncPolicyClient) GetSyncJobLog(ctx context.Context, in *GetSyncJobLogRequest, opts ...grpc.CallOption) (*GetSyncJobLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncJobLogResponse)
	err := c.cc.Invoke(ctx, SyncPolicy_GetSyncJobLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncPolicyServer is the server API for SyncPolicy service.
// All implementations should embed UnimplementedSyncPolicyServer
// for forward compatibility.
type SyncPolicyServer interface {
	// ListSyncPolicies lists all sync policies.
	ListSyncPolicies(context.Context, *ListSyncPoliciesRequest) (*ListSyncPoliciesResponse, error)
	// GetSyncPolicy gets a sync policy by id.
	GetSyncPolicy(context.Context, *GetSyncPolicyRequest) (*GetSyncPolicyResponse, error)
	// CreateSyncPolicy creates a new sync policy.
	CreateSyncPolicy(context.Context, *CreateSyncPolicyRequest) (*CreateSyncPolicyResponse, error)
	// UpdateSyncPolicy updates a sync policy.
	UpdateSyncPolicy(context.Context, *UpdateSyncPolicyRequest) (*UpdateSyncPolicyResponse, error)
	// DeleteSyncPolicy deletes a sync policy.
	DeleteSyncPolicy(context.Context, *DeleteSyncPolicyRequest) (*DeleteSyncPolicyResponse, error)
	// CreateSyncTask creates a new sync task.
	CreateSyncTask(context.Context, *CreateSyncTaskRequest) (*CreateSyncTaskResponse, error)
	// ListSyncTasks lists all sync tasks.
	ListSyncTasks(context.Context, *ListSyncTasksRequest) (*ListSyncTasksResponse, error)
	// StopSyncTask stops a sync task.
	StopSyncTask(context.Context, *StopSyncTaskRequest) (*StopSyncTaskResponse, error)
	// ListSyncJobs lists all sync jobs.
	ListSyncJobs(context.Context, *ListSyncJobsRequest) (*ListSyncJobsResponse, error)
	// GetSyncJobLog gets the log of a sync job.
	GetSyncJobLog(context.Context, *GetSyncJobLogRequest) (*GetSyncJobLogResponse, error)
}

// UnimplementedSyncPolicyServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncPolicyServer struct{}

func (UnimplementedSyncPolicyServer) ListSyncPolicies(context.Context, *ListSyncPoliciesRequest) (*ListSyncPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSyncPolicies not implemented")
}
func (UnimplementedSyncPolicyServer) GetSyncPolicy(context.Context, *GetSyncPolicyRequest) (*GetSyncPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncPolicy not implemented")
}
func (UnimplementedSyncPolicyServer) CreateSyncPolicy(context.Context, *CreateSyncPolicyRequest) (*CreateSyncPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSyncPolicy not implemented")
}
func (UnimplementedSyncPolicyServer) UpdateSyncPolicy(context.Context, *UpdateSyncPolicyRequest) (*UpdateSyncPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSyncPolicy not implemented")
}
func (UnimplementedSyncPolicyServer) DeleteSyncPolicy(context.Context, *DeleteSyncPolicyRequest) (*DeleteSyncPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSyncPolicy not implemented")
}
func (UnimplementedSyncPolicyServer) CreateSyncTask(context.Context, *CreateSyncTaskRequest) (*CreateSyncTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSyncTask not implemented")
}
func (UnimplementedSyncPolicyServer) ListSyncTasks(context.Context, *ListSyncTasksRequest) (*ListSyncTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSyncTasks not implemented")
}
func (UnimplementedSyncPolicyServer) StopSyncTask(context.Context, *StopSyncTaskRequest) (*StopSyncTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSyncTask not implemented")
}
func (UnimplementedSyncPolicyServer) ListSyncJobs(context.Context, *ListSyncJobsRequest) (*ListSyncJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSyncJobs not implemented")
}
func (UnimplementedSyncPolicyServer) GetSyncJobLog(context.Context, *GetSyncJobLogRequest) (*GetSyncJobLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncJobLog not implemented")
}
func (UnimplementedSyncPolicyServer) testEmbeddedByValue() {}

// UnsafeSyncPolicyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncPolicyServer will
// result in compilation errors.
type UnsafeSyncPolicyServer interface {
	mustEmbedUnimplementedSyncPolicyServer()
}

func RegisterSyncPolicyServer(s grpc.ServiceRegistrar, srv SyncPolicyServer) {
	// If the following call panics, it indicates UnimplementedSyncPolicyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncPolicy_ServiceDesc, srv)
}

func _SyncPolicy_ListSyncPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSyncPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).ListSyncPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_ListSyncPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).ListSyncPolicies(ctx, req.(*ListSyncPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_GetSyncPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).GetSyncPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_GetSyncPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).GetSyncPolicy(ctx, req.(*GetSyncPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_CreateSyncPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSyncPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).CreateSyncPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_CreateSyncPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).CreateSyncPolicy(ctx, req.(*CreateSyncPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_UpdateSyncPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSyncPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).UpdateSyncPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_UpdateSyncPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).UpdateSyncPolicy(ctx, req.(*UpdateSyncPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_DeleteSyncPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSyncPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).DeleteSyncPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_DeleteSyncPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).DeleteSyncPolicy(ctx, req.(*DeleteSyncPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_CreateSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).CreateSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_CreateSyncTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).CreateSyncTask(ctx, req.(*CreateSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_ListSyncTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSyncTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).ListSyncTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_ListSyncTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).ListSyncTasks(ctx, req.(*ListSyncTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_StopSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSyncTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).StopSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_StopSyncTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).StopSyncTask(ctx, req.(*StopSyncTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_ListSyncJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSyncJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).ListSyncJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_ListSyncJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).ListSyncJobs(ctx, req.(*ListSyncJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncPolicy_GetSyncJobLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncJobLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncPolicyServer).GetSyncJobLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncPolicy_GetSyncJobLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncPolicyServer).GetSyncJobLog(ctx, req.(*GetSyncJobLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncPolicy_ServiceDesc is the grpc.ServiceDesc for SyncPolicy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncPolicy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.SyncPolicy",
	HandlerType: (*SyncPolicyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSyncPolicies",
			Handler:    _SyncPolicy_ListSyncPolicies_Handler,
		},
		{
			MethodName: "GetSyncPolicy",
			Handler:    _SyncPolicy_GetSyncPolicy_Handler,
		},
		{
			MethodName: "CreateSyncPolicy",
			Handler:    _SyncPolicy_CreateSyncPolicy_Handler,
		},
		{
			MethodName: "UpdateSyncPolicy",
			Handler:    _SyncPolicy_UpdateSyncPolicy_Handler,
		},
		{
			MethodName: "DeleteSyncPolicy",
			Handler:    _SyncPolicy_DeleteSyncPolicy_Handler,
		},
		{
			MethodName: "CreateSyncTask",
			Handler:    _SyncPolicy_CreateSyncTask_Handler,
		},
		{
			MethodName: "ListSyncTasks",
			Handler:    _SyncPolicy_ListSyncTasks_Handler,
		},
		{
			MethodName: "StopSyncTask",
			Handler:    _SyncPolicy_StopSyncTask_Handler,
		},
		{
			MethodName: "ListSyncJobs",
			Handler:    _SyncPolicy_ListSyncJobs_Handler,
		},
		{
			MethodName: "GetSyncJobLog",
			Handler:    _SyncPolicy_GetSyncJobLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/sync_policy.proto",
}
