// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/sync_policy.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncPolicyType int32

const (
	SyncPolicyType_SYNC_POLICY_TYPE_UNSPECIFIED SyncPolicyType = 0
	SyncPolicyType_SYNC_POLICY_TYPE_PULL_BASE   SyncPolicyType = 1
	SyncPolicyType_SYNC_POLICY_TYPE_PUSH_BASE   SyncPolicyType = 2
)

// Enum value maps for SyncPolicyType.
var (
	SyncPolicyType_name = map[int32]string{
		0: "SYNC_POLICY_TYPE_UNSPECIFIED",
		1: "SYNC_POLICY_TYPE_PULL_BASE",
		2: "SYNC_POLICY_TYPE_PUSH_BASE",
	}
	SyncPolicyType_value = map[string]int32{
		"SYNC_POLICY_TYPE_UNSPECIFIED": 0,
		"SYNC_POLICY_TYPE_PULL_BASE":   1,
		"SYNC_POLICY_TYPE_PUSH_BASE":   2,
	}
)

func (x SyncPolicyType) Enum() *SyncPolicyType {
	p := new(SyncPolicyType)
	*p = x
	return p
}

func (x SyncPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_sync_policy_proto_enumTypes[0].Descriptor()
}

func (SyncPolicyType) Type() protoreflect.EnumType {
	return &file_v1alpha1_sync_policy_proto_enumTypes[0]
}

func (x SyncPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncPolicyType.Descriptor instead.
func (SyncPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{0}
}

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCE_TYPE_MODEL       ResourceType = 1
	ResourceType_RESOURCE_TYPE_DATASET     ResourceType = 2
	ResourceType_RESOURCE_TYPE_ALL         ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_MODEL",
		2: "RESOURCE_TYPE_DATASET",
		3: "RESOURCE_TYPE_ALL",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_MODEL":       1,
		"RESOURCE_TYPE_DATASET":     2,
		"RESOURCE_TYPE_ALL":         3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_sync_policy_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_v1alpha1_sync_policy_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{1}
}

type TriggerType int32

const (
	TriggerType_TRIGGER_TYPE_UNSPECIFIED TriggerType = 0
	TriggerType_TRIGGER_TYPE_MANUAL      TriggerType = 1
	TriggerType_TRIGGER_TYPE_SCHEDULED   TriggerType = 2
)

// Enum value maps for TriggerType.
var (
	TriggerType_name = map[int32]string{
		0: "TRIGGER_TYPE_UNSPECIFIED",
		1: "TRIGGER_TYPE_MANUAL",
		2: "TRIGGER_TYPE_SCHEDULED",
	}
	TriggerType_value = map[string]int32{
		"TRIGGER_TYPE_UNSPECIFIED": 0,
		"TRIGGER_TYPE_MANUAL":      1,
		"TRIGGER_TYPE_SCHEDULED":   2,
	}
)

func (x TriggerType) Enum() *TriggerType {
	p := new(TriggerType)
	*p = x
	return p
}

func (x TriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_sync_policy_proto_enumTypes[2].Descriptor()
}

func (TriggerType) Type() protoreflect.EnumType {
	return &file_v1alpha1_sync_policy_proto_enumTypes[2]
}

func (x TriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerType.Descriptor instead.
func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{2}
}

type SyncTaskStatus int32

const (
	SyncTaskStatus_SYNC_TASK_STATUS_UNSPECIFIED SyncTaskStatus = 0
	SyncTaskStatus_SYNC_TASK_STATUS_RUNNING     SyncTaskStatus = 1
	SyncTaskStatus_SYNC_TASK_STATUS_SUCCEEDED   SyncTaskStatus = 2
	SyncTaskStatus_SYNC_TASK_STATUS_FAILED      SyncTaskStatus = 3
	SyncTaskStatus_SYNC_TASK_STATUS_STOPPED     SyncTaskStatus = 4
)

// Enum value maps for SyncTaskStatus.
var (
	SyncTaskStatus_name = map[int32]string{
		0: "SYNC_TASK_STATUS_UNSPECIFIED",
		1: "SYNC_TASK_STATUS_RUNNING",
		2: "SYNC_TASK_STATUS_SUCCEEDED",
		3: "SYNC_TASK_STATUS_FAILED",
		4: "SYNC_TASK_STATUS_STOPPED",
	}
	SyncTaskStatus_value = map[string]int32{
		"SYNC_TASK_STATUS_UNSPECIFIED": 0,
		"SYNC_TASK_STATUS_RUNNING":     1,
		"SYNC_TASK_STATUS_SUCCEEDED":   2,
		"SYNC_TASK_STATUS_FAILED":      3,
		"SYNC_TASK_STATUS_STOPPED":     4,
	}
)

func (x SyncTaskStatus) Enum() *SyncTaskStatus {
	p := new(SyncTaskStatus)
	*p = x
	return p
}

func (x SyncTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_sync_policy_proto_enumTypes[3].Descriptor()
}

func (SyncTaskStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_sync_policy_proto_enumTypes[3]
}

func (x SyncTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncTaskStatus.Descriptor instead.
func (SyncTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{3}
}

type PullBasePolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceRegistryId   uint32                 `protobuf:"varint,1,opt,name=source_registry_id,json=sourceRegistryId,proto3" json:"source_registry_id,omitempty"`
	ResourceName       string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceTypes      []ResourceType         `protobuf:"varint,3,rep,packed,name=resource_types,json=resourceTypes,proto3,enum=matrixhub.v1alpha1.ResourceType" json:"resource_types,omitempty"`
	TargetResourceName string                 `protobuf:"bytes,4,opt,name=target_resource_name,json=targetResourceName,proto3" json:"target_resource_name,omitempty"`
	// post or put do not require this field.
	SourceRegistry    *Registry `protobuf:"bytes,5,opt,name=source_registry,json=sourceRegistry,proto3" json:"source_registry,omitempty"`
	TargetProjectName string    `protobuf:"bytes,6,opt,name=target_project_name,json=targetProjectName,proto3" json:"target_project_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullBasePolicy) Reset() {
	*x = PullBasePolicy{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullBasePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBasePolicy) ProtoMessage() {}

func (x *PullBasePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBasePolicy.ProtoReflect.Descriptor instead.
func (*PullBasePolicy) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PullBasePolicy) GetSourceRegistryId() uint32 {
	if x != nil {
		return x.SourceRegistryId
	}
	return 0
}

func (x *PullBasePolicy) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *PullBasePolicy) GetResourceTypes() []ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *PullBasePolicy) GetTargetResourceName() string {
	if x != nil {
		return x.TargetResourceName
	}
	return ""
}

func (x *PullBasePolicy) GetSourceRegistry() *Registry {
	if x != nil {
		return x.SourceRegistry
	}
	return nil
}

func (x *PullBasePolicy) GetTargetProjectName() string {
	if x != nil {
		return x.TargetProjectName
	}
	return ""
}

type PushBasePolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceName       string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceTypes      []ResourceType         `protobuf:"varint,2,rep,packed,name=resource_types,json=resourceTypes,proto3,enum=matrixhub.v1alpha1.ResourceType" json:"resource_types,omitempty"`
	TargetRegistryId   uint32                 `protobuf:"varint,3,opt,name=target_registry_id,json=targetRegistryId,proto3" json:"target_registry_id,omitempty"`
	TargetResourceName string                 `protobuf:"bytes,4,opt,name=target_resource_name,json=targetResourceName,proto3" json:"target_resource_name,omitempty"`
	// post or put do not require this field.
	TargetRegistry    *Registry `protobuf:"bytes,5,opt,name=target_registry,json=targetRegistry,proto3" json:"target_registry,omitempty"`
	TargetProjectName string    `protobuf:"bytes,6,opt,name=target_project_name,json=targetProjectName,proto3" json:"target_project_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushBasePolicy) Reset() {
	*x = PushBasePolicy{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBasePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBasePolicy) ProtoMessage() {}

func (x *PushBasePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBasePolicy.ProtoReflect.Descriptor instead.
func (*PushBasePolicy) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PushBasePolicy) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *PushBasePolicy) GetResourceTypes() []ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *PushBasePolicy) GetTargetRegistryId() uint32 {
	if x != nil {
		return x.TargetRegistryId
	}
	return 0
}

func (x *PushBasePolicy) GetTargetResourceName() string {
	if x != nil {
		return x.TargetResourceName
	}
	return ""
}

func (x *PushBasePolicy) GetTargetRegistry() *Registry {
	if x != nil {
		return x.TargetRegistry
	}
	return nil
}

func (x *PushBasePolicy) GetTargetProjectName() string {
	if x != nil {
		return x.TargetProjectName
	}
	return ""
}

type SyncPolicyItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PolicyType  SyncPolicyType         `protobuf:"varint,4,opt,name=policy_type,json=policyType,proto3,enum=matrixhub.v1alpha1.SyncPolicyType" json:"policy_type,omitempty"`
	TriggerType TriggerType            `protobuf:"varint,5,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// Types that are valid to be assigned to Policy:
	//
	//	*SyncPolicyItem_PullBasePolicy
	//	*SyncPolicyItem_PushBasePolicy
	Policy isSyncPolicyItem_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the sync policy.
	Bandwidth     string `protobuf:"bytes,8,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,9,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	IsDisabled    bool   `protobuf:"varint,10,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPolicyItem) Reset() {
	*x = SyncPolicyItem{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPolicyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPolicyItem) ProtoMessage() {}

func (x *SyncPolicyItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPolicyItem.ProtoReflect.Descriptor instead.
func (*SyncPolicyItem) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPolicyItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncPolicyItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncPolicyItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SyncPolicyItem) GetPolicyType() SyncPolicyType {
	if x != nil {
		return x.PolicyType
	}
	return SyncPolicyType_SYNC_POLICY_TYPE_UNSPECIFIED
}

func (x *SyncPolicyItem) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *SyncPolicyItem) GetPolicy() isSyncPolicyItem_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SyncPolicyItem) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*SyncPolicyItem_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *SyncPolicyItem) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*SyncPolicyItem_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *SyncPolicyItem) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *SyncPolicyItem) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

func (x *SyncPolicyItem) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

type isSyncPolicyItem_Policy interface {
	isSyncPolicyItem_Policy()
}

type SyncPolicyItem_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,6,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type SyncPolicyItem_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,7,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*SyncPolicyItem_PullBasePolicy) isSyncPolicyItem_Policy() {}

func (*SyncPolicyItem_PushBasePolicy) isSyncPolicyItem_Policy() {}

type CreateSyncPolicyRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PolicyType  SyncPolicyType         `protobuf:"varint,3,opt,name=policy_type,json=policyType,proto3,enum=matrixhub.v1alpha1.SyncPolicyType" json:"policy_type,omitempty"`
	TriggerType TriggerType            `protobuf:"varint,4,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// The policy to use for the sync policy.
	// only one of pull_base_policy or push_base_policy should be set.
	//
	// Types that are valid to be assigned to Policy:
	//
	//	*CreateSyncPolicyRequest_PullBasePolicy
	//	*CreateSyncPolicyRequest_PushBasePolicy
	Policy isCreateSyncPolicyRequest_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the sync policy.
	Bandwidth     string `protobuf:"bytes,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,8,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncPolicyRequest) Reset() {
	*x = CreateSyncPolicyRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncPolicyRequest) ProtoMessage() {}

func (x *CreateSyncPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateSyncPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSyncPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSyncPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSyncPolicyRequest) GetPolicyType() SyncPolicyType {
	if x != nil {
		return x.PolicyType
	}
	return SyncPolicyType_SYNC_POLICY_TYPE_UNSPECIFIED
}

func (x *CreateSyncPolicyRequest) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *CreateSyncPolicyRequest) GetPolicy() isCreateSyncPolicyRequest_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CreateSyncPolicyRequest) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*CreateSyncPolicyRequest_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *CreateSyncPolicyRequest) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*CreateSyncPolicyRequest_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *CreateSyncPolicyRequest) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *CreateSyncPolicyRequest) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

type isCreateSyncPolicyRequest_Policy interface {
	isCreateSyncPolicyRequest_Policy()
}

type CreateSyncPolicyRequest_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,5,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type CreateSyncPolicyRequest_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,6,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*CreateSyncPolicyRequest_PullBasePolicy) isCreateSyncPolicyRequest_Policy() {}

func (*CreateSyncPolicyRequest_PushBasePolicy) isCreateSyncPolicyRequest_Policy() {}

type CreateSyncPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicy    *SyncPolicyItem        `protobuf:"bytes,1,opt,name=sync_policy,json=syncPolicy,proto3" json:"sync_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncPolicyResponse) Reset() {
	*x = CreateSyncPolicyResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncPolicyResponse) ProtoMessage() {}

func (x *CreateSyncPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncPolicyResponse.ProtoReflect.Descriptor instead.
func (*CreateSyncPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSyncPolicyResponse) GetSyncPolicy() *SyncPolicyItem {
	if x != nil {
		return x.SyncPolicy
	}
	return nil
}

type UpdateSyncPolicyRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TriggerType  TriggerType            `protobuf:"varint,4,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// The policy to use for the sync policy.
	// only one of pull_base_policy or push_base_policy should be set.
	//
	// Types that are valid to be assigned to Policy:
	//
	//	*UpdateSyncPolicyRequest_PullBasePolicy
	//	*UpdateSyncPolicyRequest_PushBasePolicy
	Policy isUpdateSyncPolicyRequest_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the sync policy.
	Bandwidth     string `protobuf:"bytes,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,8,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	IsDisabled    bool   `protobuf:"varint,9,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSyncPolicyRequest) Reset() {
	*x = UpdateSyncPolicyRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSyncPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSyncPolicyRequest) ProtoMessage() {}

func (x *UpdateSyncPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSyncPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateSyncPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSyncPolicyRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

func (x *UpdateSyncPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSyncPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSyncPolicyRequest) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *UpdateSyncPolicyRequest) GetPolicy() isUpdateSyncPolicyRequest_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdateSyncPolicyRequest) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*UpdateSyncPolicyRequest_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *UpdateSyncPolicyRequest) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*UpdateSyncPolicyRequest_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *UpdateSyncPolicyRequest) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *UpdateSyncPolicyRequest) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

func (x *UpdateSyncPolicyRequest) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

type isUpdateSyncPolicyRequest_Policy interface {
	isUpdateSyncPolicyRequest_Policy()
}

type UpdateSyncPolicyRequest_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,5,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type UpdateSyncPolicyRequest_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,6,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*UpdateSyncPolicyRequest_PullBasePolicy) isUpdateSyncPolicyRequest_Policy() {}

func (*UpdateSyncPolicyRequest_PushBasePolicy) isUpdateSyncPolicyRequest_Policy() {}

type UpdateSyncPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicy    *SyncPolicyItem        `protobuf:"bytes,1,opt,name=sync_policy,json=syncPolicy,proto3" json:"sync_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSyncPolicyResponse) Reset() {
	*x = UpdateSyncPolicyResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSyncPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSyncPolicyResponse) ProtoMessage() {}

func (x *UpdateSyncPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSyncPolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateSyncPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSyncPolicyResponse) GetSyncPolicy() *SyncPolicyItem {
	if x != nil {
		return x.SyncPolicy
	}
	return nil
}

type DeleteSyncPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId  int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSyncPolicyRequest) Reset() {
	*x = DeleteSyncPolicyRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSyncPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSyncPolicyRequest) ProtoMessage() {}

func (x *DeleteSyncPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSyncPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSyncPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSyncPolicyRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

type DeleteSyncPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicy    *SyncPolicyItem        `protobuf:"bytes,1,opt,name=sync_policy,json=syncPolicy,proto3" json:"sync_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSyncPolicyResponse) Reset() {
	*x = DeleteSyncPolicyResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSyncPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSyncPolicyResponse) ProtoMessage() {}

func (x *DeleteSyncPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSyncPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteSyncPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSyncPolicyResponse) GetSyncPolicy() *SyncPolicyItem {
	if x != nil {
		return x.SyncPolicy
	}
	return nil
}

type ListSyncPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncPoliciesRequest) Reset() {
	*x = ListSyncPoliciesRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncPoliciesRequest) ProtoMessage() {}

func (x *ListSyncPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListSyncPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{9}
}

func (x *ListSyncPoliciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSyncPoliciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSyncPoliciesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListSyncPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicies  []*SyncPolicyItem      `protobuf:"bytes,1,rep,name=sync_policies,json=syncPolicies,proto3" json:"sync_policies,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncPoliciesResponse) Reset() {
	*x = ListSyncPoliciesResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncPoliciesResponse) ProtoMessage() {}

func (x *ListSyncPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListSyncPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{10}
}

func (x *ListSyncPoliciesResponse) GetSyncPolicies() []*SyncPolicyItem {
	if x != nil {
		return x.SyncPolicies
	}
	return nil
}

func (x *ListSyncPoliciesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetSyncPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId  int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncPolicyRequest) Reset() {
	*x = GetSyncPolicyRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncPolicyRequest) ProtoMessage() {}

func (x *GetSyncPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetSyncPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{11}
}

func (x *GetSyncPolicyRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

type GetSyncPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicy    *SyncPolicyItem        `protobuf:"bytes,1,opt,name=sync_policy,json=syncPolicy,proto3" json:"sync_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncPolicyResponse) Reset() {
	*x = GetSyncPolicyResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncPolicyResponse) ProtoMessage() {}

func (x *GetSyncPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetSyncPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{12}
}

func (x *GetSyncPolicyResponse) GetSyncPolicy() *SyncPolicyItem {
	if x != nil {
		return x.SyncPolicy
	}
	return nil
}

type CreateSyncTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId  int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncTaskRequest) Reset() {
	*x = CreateSyncTaskRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncTaskRequest) ProtoMessage() {}

func (x *CreateSyncTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateSyncTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSyncTaskRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

type CreateSyncTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncTaskResponse) Reset() {
	*x = CreateSyncTaskResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncTaskResponse) ProtoMessage() {}

func (x *CreateSyncTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateSyncTaskResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSyncTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SyncTask struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SyncPolicyId       int32                  `protobuf:"varint,2,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	TriggerType        TriggerType            `protobuf:"varint,3,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	Status             SyncTaskStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=matrixhub.v1alpha1.SyncTaskStatus" json:"status,omitempty"`
	StartedTimestamp   int64                  `protobuf:"varint,5,opt,name=started_timestamp,json=startedTimestamp,proto3" json:"started_timestamp,omitempty"`
	CompletedTimestamp int64                  `protobuf:"varint,6,opt,name=completed_timestamp,json=completedTimestamp,proto3" json:"completed_timestamp,omitempty"`
	TotalItems         int64                  `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	SuccessfulItems    int64                  `protobuf:"varint,8,opt,name=successful_items,json=successfulItems,proto3" json:"successful_items,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncTask) Reset() {
	*x = SyncTask{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTask) ProtoMessage() {}

func (x *SyncTask) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTask.ProtoReflect.Descriptor instead.
func (*SyncTask) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{15}
}

func (x *SyncTask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncTask) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

func (x *SyncTask) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *SyncTask) GetStatus() SyncTaskStatus {
	if x != nil {
		return x.Status
	}
	return SyncTaskStatus_SYNC_TASK_STATUS_UNSPECIFIED
}

func (x *SyncTask) GetStartedTimestamp() int64 {
	if x != nil {
		return x.StartedTimestamp
	}
	return 0
}

func (x *SyncTask) GetCompletedTimestamp() int64 {
	if x != nil {
		return x.CompletedTimestamp
	}
	return 0
}

func (x *SyncTask) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *SyncTask) GetSuccessfulItems() int64 {
	if x != nil {
		return x.SuccessfulItems
	}
	return 0
}

type ListSyncTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId  int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncTasksRequest) Reset() {
	*x = ListSyncTasksRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncTasksRequest) ProtoMessage() {}

func (x *ListSyncTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncTasksRequest.ProtoReflect.Descriptor instead.
func (*ListSyncTasksRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{16}
}

func (x *ListSyncTasksRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

func (x *ListSyncTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSyncTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSyncTasksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListSyncTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncTasks     []*SyncTask            `protobuf:"bytes,1,rep,name=sync_tasks,json=syncTasks,proto3" json:"sync_tasks,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncTasksResponse) Reset() {
	*x = ListSyncTasksResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncTasksResponse) ProtoMessage() {}

func (x *ListSyncTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncTasksResponse.ProtoReflect.Descriptor instead.
func (*ListSyncTasksResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{17}
}

func (x *ListSyncTasksResponse) GetSyncTasks() []*SyncTask {
	if x != nil {
		return x.SyncTasks
	}
	return nil
}

func (x *ListSyncTasksResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type StopSyncTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncPolicyId  int32                  `protobuf:"varint,1,opt,name=sync_policy_id,json=syncPolicyId,proto3" json:"sync_policy_id,omitempty"`
	SyncTaskId    int32                  `protobuf:"varint,2,opt,name=sync_task_id,json=syncTaskId,proto3" json:"sync_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSyncTaskRequest) Reset() {
	*x = StopSyncTaskRequest{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSyncTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSyncTaskRequest) ProtoMessage() {}

func (x *StopSyncTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSyncTaskRequest.ProtoReflect.Descriptor instead.
func (*StopSyncTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{18}
}

func (x *StopSyncTaskRequest) GetSyncPolicyId() int32 {
	if x != nil {
		return x.SyncPolicyId
	}
	return 0
}

func (x *StopSyncTaskRequest) GetSyncTaskId() int32 {
	if x != nil {
		return x.SyncTaskId
	}
	return 0
}

type StopSyncTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncTask      *SyncTask              `protobuf:"bytes,1,opt,name=sync_task,json=syncTask,proto3" json:"sync_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSyncTaskResponse) Reset() {
	*x = StopSyncTaskResponse{}
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSyncTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSyncTaskResponse) ProtoMessage() {}

func (x *StopSyncTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_sync_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSyncTaskResponse.ProtoReflect.Descriptor instead.
func (*StopSyncTaskResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_sync_policy_proto_rawDescGZIP(), []int{19}
}

func (x *StopSyncTaskResponse) GetSyncTask() *SyncTask {
	if x != nil {
		return x.SyncTask
	}
	return nil
}

var File_v1alpha1_sync_policy_proto protoreflect.FileDescriptor

const file_v1alpha1_sync_policy_proto_rawDesc = "" +
	"\n" +
	"\x1av1alpha1/sync_policy.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x14v1alpha1/utils.proto\x1a\x17v1alpha1/registry.proto\"\xd5\x02\n" +
	"\x0ePullBasePolicy\x12,\n" +
	"\x12source_registry_id\x18\x01 \x01(\rR\x10sourceRegistryId\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12G\n" +
	"\x0eresource_types\x18\x03 \x03(\x0e2 .matrixhub.v1alpha1.ResourceTypeR\rresourceTypes\x120\n" +
	"\x14target_resource_name\x18\x04 \x01(\tR\x12targetResourceName\x12E\n" +
	"\x0fsource_registry\x18\x05 \x01(\v2\x1c.matrixhub.v1alpha1.RegistryR\x0esourceRegistry\x12.\n" +
	"\x13target_project_name\x18\x06 \x01(\tR\x11targetProjectName\"\xd5\x02\n" +
	"\x0ePushBasePolicy\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12G\n" +
	"\x0eresource_types\x18\x02 \x03(\x0e2 .matrixhub.v1alpha1.ResourceTypeR\rresourceTypes\x12,\n" +
	"\x12target_registry_id\x18\x03 \x01(\rR\x10targetRegistryId\x120\n" +
	"\x14target_resource_name\x18\x04 \x01(\tR\x12targetResourceName\x12E\n" +
	"\x0ftarget_registry\x18\x05 \x01(\v2\x1c.matrixhub.v1alpha1.RegistryR\x0etargetRegistry\x12.\n" +
	"\x13target_project_name\x18\x06 \x01(\tR\x11targetProjectName\"\xeb\x03\n" +
	"\x0eSyncPolicyItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12C\n" +
	"\vpolicy_type\x18\x04 \x01(\x0e2\".matrixhub.v1alpha1.SyncPolicyTypeR\n" +
	"policyType\x12B\n" +
	"\ftrigger_type\x18\x05 \x01(\x0e2\x1f.matrixhub.v1alpha1.TriggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\a \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\b \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\t \x01(\bR\visOverwrite\x12\x1f\n" +
	"\vis_disabled\x18\n" +
	" \x01(\bR\n" +
	"isDisabledB\b\n" +
	"\x06policy\"\xc3\x03\n" +
	"\x17CreateSyncPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12C\n" +
	"\vpolicy_type\x18\x03 \x01(\x0e2\".matrixhub.v1alpha1.SyncPolicyTypeR\n" +
	"policyType\x12B\n" +
	"\ftrigger_type\x18\x04 \x01(\x0e2\x1f.matrixhub.v1alpha1.TriggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x05 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\b \x01(\bR\visOverwriteB\b\n" +
	"\x06policy\"_\n" +
	"\x18CreateSyncPolicyResponse\x12C\n" +
	"\vsync_policy\x18\x01 \x01(\v2\".matrixhub.v1alpha1.SyncPolicyItemR\n" +
	"syncPolicy\"\xc5\x03\n" +
	"\x17UpdateSyncPolicyRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\ftrigger_type\x18\x04 \x01(\x0e2\x1f.matrixhub.v1alpha1.TriggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x05 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\b \x01(\bR\visOverwrite\x12\x1f\n" +
	"\vis_disabled\x18\t \x01(\bR\n" +
	"isDisabledB\b\n" +
	"\x06policy\"_\n" +
	"\x18UpdateSyncPolicyResponse\x12C\n" +
	"\vsync_policy\x18\x01 \x01(\v2\".matrixhub.v1alpha1.SyncPolicyItemR\n" +
	"syncPolicy\"?\n" +
	"\x17DeleteSyncPolicyRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\"_\n" +
	"\x18DeleteSyncPolicyResponse\x12C\n" +
	"\vsync_policy\x18\x01 \x01(\v2\".matrixhub.v1alpha1.SyncPolicyItemR\n" +
	"syncPolicy\"b\n" +
	"\x17ListSyncPoliciesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xa3\x01\n" +
	"\x18ListSyncPoliciesResponse\x12G\n" +
	"\rsync_policies\x18\x01 \x03(\v2\".matrixhub.v1alpha1.SyncPolicyItemR\fsyncPolicies\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"<\n" +
	"\x14GetSyncPolicyRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\"\\\n" +
	"\x15GetSyncPolicyResponse\x12C\n" +
	"\vsync_policy\x18\x01 \x01(\v2\".matrixhub.v1alpha1.SyncPolicyItemR\n" +
	"syncPolicy\"=\n" +
	"\x15CreateSyncTaskRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\"(\n" +
	"\x16CreateSyncTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xea\x02\n" +
	"\bSyncTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12$\n" +
	"\x0esync_policy_id\x18\x02 \x01(\x05R\fsyncPolicyId\x12B\n" +
	"\ftrigger_type\x18\x03 \x01(\x0e2\x1f.matrixhub.v1alpha1.TriggerTypeR\vtriggerType\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".matrixhub.v1alpha1.SyncTaskStatusR\x06status\x12+\n" +
	"\x11started_timestamp\x18\x05 \x01(\x03R\x10startedTimestamp\x12/\n" +
	"\x13completed_timestamp\x18\x06 \x01(\x03R\x12completedTimestamp\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x03R\n" +
	"totalItems\x12)\n" +
	"\x10successful_items\x18\b \x01(\x03R\x0fsuccessfulItems\"\x85\x01\n" +
	"\x14ListSyncTasksRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\x94\x01\n" +
	"\x15ListSyncTasksResponse\x12;\n" +
	"\n" +
	"sync_tasks\x18\x01 \x03(\v2\x1c.matrixhub.v1alpha1.SyncTaskR\tsyncTasks\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"]\n" +
	"\x13StopSyncTaskRequest\x12$\n" +
	"\x0esync_policy_id\x18\x01 \x01(\x05R\fsyncPolicyId\x12 \n" +
	"\fsync_task_id\x18\x02 \x01(\x05R\n" +
	"syncTaskId\"Q\n" +
	"\x14StopSyncTaskResponse\x129\n" +
	"\tsync_task\x18\x01 \x01(\v2\x1c.matrixhub.v1alpha1.SyncTaskR\bsyncTask*r\n" +
	"\x0eSyncPolicyType\x12 \n" +
	"\x1cSYNC_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSYNC_POLICY_TYPE_PULL_BASE\x10\x01\x12\x1e\n" +
	"\x1aSYNC_POLICY_TYPE_PUSH_BASE\x10\x02*x\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESOURCE_TYPE_MODEL\x10\x01\x12\x19\n" +
	"\x15RESOURCE_TYPE_DATASET\x10\x02\x12\x15\n" +
	"\x11RESOURCE_TYPE_ALL\x10\x03*`\n" +
	"\vTriggerType\x12\x1c\n" +
	"\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRIGGER_TYPE_MANUAL\x10\x01\x12\x1a\n" +
	"\x16TRIGGER_TYPE_SCHEDULED\x10\x02*\xab\x01\n" +
	"\x0eSyncTaskStatus\x12 \n" +
	"\x1cSYNC_TASK_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SYNC_TASK_STATUS_RUNNING\x10\x01\x12\x1e\n" +
	"\x1aSYNC_TASK_STATUS_SUCCEEDED\x10\x02\x12\x1b\n" +
	"\x17SYNC_TASK_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18SYNC_TASK_STATUS_STOPPED\x10\x042\xb1\n" +
	"\n" +
	"\n" +
	"SyncPolicy\x12\x92\x01\n" +
	"\x10ListSyncPolicies\x12+.matrixhub.v1alpha1.ListSyncPoliciesRequest\x1a,.matrixhub.v1alpha1.ListSyncPoliciesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1alpha1/sync-policies\x12\x9a\x01\n" +
	"\rGetSyncPolicy\x12(.matrixhub.v1alpha1.GetSyncPolicyRequest\x1a).matrixhub.v1alpha1.GetSyncPolicyResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1alpha1/sync-policies/{sync_policy_id}\x12\x95\x01\n" +
	"\x10CreateSyncPolicy\x12+.matrixhub.v1alpha1.CreateSyncPolicyRequest\x1a,.matrixhub.v1alpha1.CreateSyncPolicyResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1alpha1/sync-policies\x12\xa6\x01\n" +
	"\x10UpdateSyncPolicy\x12+.matrixhub.v1alpha1.UpdateSyncPolicyRequest\x1a,.matrixhub.v1alpha1.UpdateSyncPolicyResponse\"7\x82\xd3\xe4\x93\x021:\x01*\x1a,/api/v1alpha1/sync-policies/{sync_policy_id}\x12\xa3\x01\n" +
	"\x10DeleteSyncPolicy\x12+.matrixhub.v1alpha1.DeleteSyncPolicyRequest\x1a,.matrixhub.v1alpha1.DeleteSyncPolicyResponse\"4\x82\xd3\xe4\x93\x02.*,/api/v1alpha1/sync-policies/{sync_policy_id}\x12\xa8\x01\n" +
	"\x0eCreateSyncTask\x12).matrixhub.v1alpha1.CreateSyncTaskRequest\x1a*.matrixhub.v1alpha1.CreateSyncTaskResponse\"?\x82\xd3\xe4\x93\x029\"7/api/v1alpha1/sync-policies/{sync_policy_id}/sync-tasks\x12\xa5\x01\n" +
	"\rListSyncTasks\x12(.matrixhub.v1alpha1.ListSyncTasksRequest\x1a).matrixhub.v1alpha1.ListSyncTasksResponse\"?\x82\xd3\xe4\x93\x029\x127/api/v1alpha1/sync-policies/{sync_policy_id}/sync-tasks\x12\xb6\x01\n" +
	"\fStopSyncTask\x12'.matrixhub.v1alpha1.StopSyncTaskRequest\x1a(.matrixhub.v1alpha1.StopSyncTaskResponse\"S\x82\xd3\xe4\x93\x02M\"K/api/v1alpha1/sync-policies/{sync_policy_id}/sync-tasks/{sync_task_id}/stopB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_sync_policy_proto_rawDescOnce sync.Once
	file_v1alpha1_sync_policy_proto_rawDescData []byte
)

func file_v1alpha1_sync_policy_proto_rawDescGZIP() []byte {
	file_v1alpha1_sync_policy_proto_rawDescOnce.Do(func() {
		file_v1alpha1_sync_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_sync_policy_proto_rawDesc), len(file_v1alpha1_sync_policy_proto_rawDesc)))
	})
	return file_v1alpha1_sync_policy_proto_rawDescData
}

var file_v1alpha1_sync_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1alpha1_sync_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1alpha1_sync_policy_proto_goTypes = []any{
	(SyncPolicyType)(0),              // 0: matrixhub.v1alpha1.SyncPolicyType
	(ResourceType)(0),                // 1: matrixhub.v1alpha1.ResourceType
	(TriggerType)(0),                 // 2: matrixhub.v1alpha1.TriggerType
	(SyncTaskStatus)(0),              // 3: matrixhub.v1alpha1.SyncTaskStatus
	(*PullBasePolicy)(nil),           // 4: matrixhub.v1alpha1.PullBasePolicy
	(*PushBasePolicy)(nil),           // 5: matrixhub.v1alpha1.PushBasePolicy
	(*SyncPolicyItem)(nil),           // 6: matrixhub.v1alpha1.SyncPolicyItem
	(*CreateSyncPolicyRequest)(nil),  // 7: matrixhub.v1alpha1.CreateSyncPolicyRequest
	(*CreateSyncPolicyResponse)(nil), // 8: matrixhub.v1alpha1.CreateSyncPolicyResponse
	(*UpdateSyncPolicyRequest)(nil),  // 9: matrixhub.v1alpha1.UpdateSyncPolicyRequest
	(*UpdateSyncPolicyResponse)(nil), // 10: matrixhub.v1alpha1.UpdateSyncPolicyResponse
	(*DeleteSyncPolicyRequest)(nil),  // 11: matrixhub.v1alpha1.DeleteSyncPolicyRequest
	(*DeleteSyncPolicyResponse)(nil), // 12: matrixhub.v1alpha1.DeleteSyncPolicyResponse
	(*ListSyncPoliciesRequest)(nil),  // 13: matrixhub.v1alpha1.ListSyncPoliciesRequest
	(*ListSyncPoliciesResponse)(nil), // 14: matrixhub.v1alpha1.ListSyncPoliciesResponse
	(*GetSyncPolicyRequest)(nil),     // 15: matrixhub.v1alpha1.GetSyncPolicyRequest
	(*GetSyncPolicyResponse)(nil),    // 16: matrixhub.v1alpha1.GetSyncPolicyResponse
	(*CreateSyncTaskRequest)(nil),    // 17: matrixhub.v1alpha1.CreateSyncTaskRequest
	(*CreateSyncTaskResponse)(nil),   // 18: matrixhub.v1alpha1.CreateSyncTaskResponse
	(*SyncTask)(nil),                 // 19: matrixhub.v1alpha1.SyncTask
	(*ListSyncTasksRequest)(nil),     // 20: matrixhub.v1alpha1.ListSyncTasksRequest
	(*ListSyncTasksResponse)(nil),    // 21: matrixhub.v1alpha1.ListSyncTasksResponse
	(*StopSyncTaskRequest)(nil),      // 22: matrixhub.v1alpha1.StopSyncTaskRequest
	(*StopSyncTaskResponse)(nil),     // 23: matrixhub.v1alpha1.StopSyncTaskResponse
	(*Registry)(nil),                 // 24: matrixhub.v1alpha1.Registry
	(*Pagination)(nil),               // 25: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_sync_policy_proto_depIdxs = []int32{
	1,  // 0: matrixhub.v1alpha1.PullBasePolicy.resource_types:type_name -> matrixhub.v1alpha1.ResourceType
	24, // 1: matrixhub.v1alpha1.PullBasePolicy.source_registry:type_name -> matrixhub.v1alpha1.Registry
	1,  // 2: matrixhub.v1alpha1.PushBasePolicy.resource_types:type_name -> matrixhub.v1alpha1.ResourceType
	24, // 3: matrixhub.v1alpha1.PushBasePolicy.target_registry:type_name -> matrixhub.v1alpha1.Registry
	0,  // 4: matrixhub.v1alpha1.SyncPolicyItem.policy_type:type_name -> matrixhub.v1alpha1.SyncPolicyType
	2,  // 5: matrixhub.v1alpha1.SyncPolicyItem.trigger_type:type_name -> matrixhub.v1alpha1.TriggerType
	4,  // 6: matrixhub.v1alpha1.SyncPolicyItem.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 7: matrixhub.v1alpha1.SyncPolicyItem.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	0,  // 8: matrixhub.v1alpha1.CreateSyncPolicyRequest.policy_type:type_name -> matrixhub.v1alpha1.SyncPolicyType
	2,  // 9: matrixhub.v1alpha1.CreateSyncPolicyRequest.trigger_type:type_name -> matrixhub.v1alpha1.TriggerType
	4,  // 10: matrixhub.v1alpha1.CreateSyncPolicyRequest.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 11: matrixhub.v1alpha1.CreateSyncPolicyRequest.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	6,  // 12: matrixhub.v1alpha1.CreateSyncPolicyResponse.sync_policy:type_name -> matrixhub.v1alpha1.SyncPolicyItem
	2,  // 13: matrixhub.v1alpha1.UpdateSyncPolicyRequest.trigger_type:type_name -> matrixhub.v1alpha1.TriggerType
	4,  // 14: matrixhub.v1alpha1.UpdateSyncPolicyRequest.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 15: matrixhub.v1alpha1.UpdateSyncPolicyRequest.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	6,  // 16: matrixhub.v1alpha1.UpdateSyncPolicyResponse.sync_policy:type_name -> matrixhub.v1alpha1.SyncPolicyItem
	6,  // 17: matrixhub.v1alpha1.DeleteSyncPolicyResponse.sync_policy:type_name -> matrixhub.v1alpha1.SyncPolicyItem
	6,  // 18: matrixhub.v1alpha1.ListSyncPoliciesResponse.sync_policies:type_name -> matrixhub.v1alpha1.SyncPolicyItem
	25, // 19: matrixhub.v1alpha1.ListSyncPoliciesResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	6,  // 20: matrixhub.v1alpha1.GetSyncPolicyResponse.sync_policy:type_name -> matrixhub.v1alpha1.SyncPolicyItem
	2,  // 21: matrixhub.v1alpha1.SyncTask.trigger_type:type_name -> matrixhub.v1alpha1.TriggerType
	3,  // 22: matrixhub.v1alpha1.SyncTask.status:type_name -> matrixhub.v1alpha1.SyncTaskStatus
	19, // 23: matrixhub.v1alpha1.ListSyncTasksResponse.sync_tasks:type_name -> matrixhub.v1alpha1.SyncTask
	25, // 24: matrixhub.v1alpha1.ListSyncTasksResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	19, // 25: matrixhub.v1alpha1.StopSyncTaskResponse.sync_task:type_name -> matrixhub.v1alpha1.SyncTask
	13, // 26: matrixhub.v1alpha1.SyncPolicy.ListSyncPolicies:input_type -> matrixhub.v1alpha1.ListSyncPoliciesRequest
	15, // 27: matrixhub.v1alpha1.SyncPolicy.GetSyncPolicy:input_type -> matrixhub.v1alpha1.GetSyncPolicyRequest
	7,  // 28: matrixhub.v1alpha1.SyncPolicy.CreateSyncPolicy:input_type -> matrixhub.v1alpha1.CreateSyncPolicyRequest
	9,  // 29: matrixhub.v1alpha1.SyncPolicy.UpdateSyncPolicy:input_type -> matrixhub.v1alpha1.UpdateSyncPolicyRequest
	11, // 30: matrixhub.v1alpha1.SyncPolicy.DeleteSyncPolicy:input_type -> matrixhub.v1alpha1.DeleteSyncPolicyRequest
	17, // 31: matrixhub.v1alpha1.SyncPolicy.CreateSyncTask:input_type -> matrixhub.v1alpha1.CreateSyncTaskRequest
	20, // 32: matrixhub.v1alpha1.SyncPolicy.ListSyncTasks:input_type -> matrixhub.v1alpha1.ListSyncTasksRequest
	22, // 33: matrixhub.v1alpha1.SyncPolicy.StopSyncTask:input_type -> matrixhub.v1alpha1.StopSyncTaskRequest
	14, // 34: matrixhub.v1alpha1.SyncPolicy.ListSyncPolicies:output_type -> matrixhub.v1alpha1.ListSyncPoliciesResponse
	16, // 35: matrixhub.v1alpha1.SyncPolicy.GetSyncPolicy:output_type -> matrixhub.v1alpha1.GetSyncPolicyResponse
	8,  // 36: matrixhub.v1alpha1.SyncPolicy.CreateSyncPolicy:output_type -> matrixhub.v1alpha1.CreateSyncPolicyResponse
	10, // 37: matrixhub.v1alpha1.SyncPolicy.UpdateSyncPolicy:output_type -> matrixhub.v1alpha1.UpdateSyncPolicyResponse
	12, // 38: matrixhub.v1alpha1.SyncPolicy.DeleteSyncPolicy:output_type -> matrixhub.v1alpha1.DeleteSyncPolicyResponse
	18, // 39: matrixhub.v1alpha1.SyncPolicy.CreateSyncTask:output_type -> matrixhub.v1alpha1.CreateSyncTaskResponse
	21, // 40: matrixhub.v1alpha1.SyncPolicy.ListSyncTasks:output_type -> matrixhub.v1alpha1.ListSyncTasksResponse
	23, // 41: matrixhub.v1alpha1.SyncPolicy.StopSyncTask:output_type -> matrixhub.v1alpha1.StopSyncTaskResponse
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_v1alpha1_sync_policy_proto_init() }
func file_v1alpha1_sync_policy_proto_init() {
	if File_v1alpha1_sync_policy_proto != nil {
		return
	}
	file_v1alpha1_utils_proto_init()
	file_v1alpha1_registry_proto_init()
	file_v1alpha1_sync_policy_proto_msgTypes[2].OneofWrappers = []any{
		(*SyncPolicyItem_PullBasePolicy)(nil),
		(*SyncPolicyItem_PushBasePolicy)(nil),
	}
	file_v1alpha1_sync_policy_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateSyncPolicyRequest_PullBasePolicy)(nil),
		(*CreateSyncPolicyRequest_PushBasePolicy)(nil),
	}
	file_v1alpha1_sync_policy_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdateSyncPolicyRequest_PullBasePolicy)(nil),
		(*UpdateSyncPolicyRequest_PushBasePolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_sync_policy_proto_rawDesc), len(file_v1alpha1_sync_policy_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_sync_policy_proto_goTypes,
		DependencyIndexes: file_v1alpha1_sync_policy_proto_depIdxs,
		EnumInfos:         file_v1alpha1_sync_policy_proto_enumTypes,
		MessageInfos:      file_v1alpha1_sync_policy_proto_msgTypes,
	}.Build()
	File_v1alpha1_sync_policy_proto = out.File
	file_v1alpha1_sync_policy_proto_goTypes = nil
	file_v1alpha1_sync_policy_proto_depIdxs = nil
}
